version: '3.7'

services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    ports:
      - "8080:8080"
    environment:
      - CAMUNDA_RUN_ADMIN_USER=admin
      - CAMUNDA_RUN_ADMIN_PASSWORD=admin
    volumes:
      - ./:/camunda/configuration/resources/
